### ISSUE TITLE
Fails to compile on rustc 1.32.0-nightly

### ISSUE THREAD

**Issue by brendanzab** [wycats/language-reporting#1]
When compiling I get the following error:

```
error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
 --> src/emitter.rs:4:5
  |
4 | use log;
  |     ^^^ not an extern crate passed with `--extern`
  |
  = help: add #![feature(uniform_paths)] to the crate attributes to enable
note: this import refers to the macro imported here
 --> src/emitter.rs:4:5
  |
4 | use log;
  |     ^^^
```
